### ISSUE TITLE
View 역할 범위에 대한 궁금증

### ISSUE THREAD

**Issue by wmakerjun** [woowacourse/fe-library#1]
![스크린샷 2021-02-17 오전 11 04 47](https://user-images.githubusercontent.com/50367798/108146139-014a6400-7110-11eb-86bf-34e1d5bd7630.png)
![스크린샷 2021-02-17 오전 11 04 55](https://user-images.githubusercontent.com/50367798/108146146-04ddeb00-7110-11eb-868c-e971d9c557d4.png)

### 링크
https://forum.sencha.com/forum/showthread.php?283525-Best-place-to-put-the-event-listeners-(Controller-or-View)

https://medium.com/@jang.wangsu/%EC%84%A4%EA%B3%84-%EC%9A%A9%EC%96%B4-%EC%9D%91%EC[…]7%91%EB%8F%84%EC%99%80-%EA%B2%B0%ED%95%A9%EB%8F%84-b5e2b7b210ff

**Comment by wmakerjun** [comment]
Thread
﻿fe-3기-질문방


인치(한창희)  9 days ago
저도 카일과 같은 이유로 처음에는 이벤트 리스너와 같은 부분을 View에 넣어야 된다고 생각했는데
최종적으론 Controller에 넣는게 더 적절하다고 생각합니다.
아래 글이 많은 영향을 줬습니다 ㅎㅎ
https://forum.sencha.com/forum/showthread.php?283525-Best-place-to-put-the-event-listeners-(Controller-or-View)
forum.sencha.com
Best place to put the event listeners (Controller or View)
Hi, I am new to EXTjs and I have a doubt regarding the placing of the event listener So, If I have two different panels in my application and each have two buttons. Should I define my my event listeners for the two buttons and their subsequent actions in the controller OR Should I be placing the listeners in the individual view itself?
:god:
2


카일(임광열)  9 days ago
@인치 아티클 고마워요! 찬찬히 읽어볼게요 :slightly_smiling_face:
:+1:
1


파노(전환오)  9 days ago
재사용성을 놓고 봤을때 다른 컨트롤러가 붙어도 동작이 가능하려면 뷰는 렌더링만 담당하는게 좋을것같네요
:pray:
2
:god:
2


파노(전환오)  9 days ago
동작에 변화를 주려면 컨트롤러단만 보면 되니까 유지보수도 쉬워질것같아요. (edited) 
:king:
2


파노(전환오)  9 days ago
https://medium.com/@jang.wangsu/%EC%84%A4%EA%B3%84-%EC%9A%A9%EC%96%B4-%EC%9D%91%EC[…]7%91%EB%8F%84%EC%99%80-%EA%B2%B0%ED%95%A9%EB%8F%84-b5e2b7b210ff
MediumMedium
[설계 용어] 응집도와 결합도
High Cohesion, Low Coupling, 응집도와 결합도 라는 설계관련 용어는 프로그래밍에 익숙하지 않은 사람들에게는 쉽게 익숙해지기가 처음에는 어려울 것 같아요.
Reading time
7 min read
Oct 7th, 2020 (169 kB)
https://miro.medium.com/max/1200/1*0GRGRKqopkdt6anDGwESWQ.png




서니(박선희)  9 days ago
@티케(조은현) 저희는 View 부분에 이벤트 리스너를 넣었습니다. 사용자에게 보여지는 부분과 관련되는 로직이라고 생각해서 View 에서 사용자의 입력을 받는 것이 맞다고 생각했고, View 에서는 click 과 같은 이벤트를 받아서 컨트롤러에 전달하고, 그 이벤트에 대한 핸들링은 Controller 에서 처리하는 식으로 했어요.

파노(전환오)  9 days ago
이거 보고있는데 좋은거같아여

카일(임광열)  9 days ago
다들 감사합니다 ! 데일리 미팅 후에 차근차근 읽어보고 또 얘기해 봐야겠네요 ㅎㅎ

티케(조은현)  9 days ago
@서니(박선희) 추가로 덧붙이자면 저희는 컨트롤러의 부분은 정말로 뷰와 모델을 연결해주는 역할이라고만 생각해서 이벤트를 걸어주는 것은 View에서, 처리하는 것은 Controller에서 했습니다.
:+1:
1

**Comment by eastjun** [comment]
카일(임광열) Feb 8th at 11:56 AM
페어와 MVC 패턴에 대해 논의하던 중 View 의 역할 범위에 대해 궁금한 점이 생겼는데요. 서로 의견이 대립된 부분은 이렇습니다.
View는 M-C 에서 다룬 데이터와 비즈니스 로직을 기반으로 최종 렌더링 부분만 담당한다.
View는 사용자가 가장 처음 마주하는 부분이기 때문에 최종 렌더링 뿐만 아니라 입력 관련 로직도 처리해야 한다. (이벤트 리스너 등)
저번에 올라온 미키의 글도 비슷한 이슈였던 것 같은데, 이와 관련해 다른 분들의 생각도 들어보고 싶습니다 ㅎㅎ (edited) 
:+1:
4

9 replies

인치(한창희)  9 days ago
저도 카일과 같은 이유로 처음에는 이벤트 리스너와 같은 부분을 View에 넣어야 된다고 생각했는데
최종적으론 Controller에 넣는게 더 적절하다고 생각합니다.
아래 글이 많은 영향을 줬습니다 ㅎㅎ
https://forum.sencha.com/forum/showthread.php?283525-Best-place-to-put-the-event-listeners-(Controller-or-View)
forum.sencha.com
Best place to put the event listeners (Controller or View)
Hi, I am new to EXTjs and I have a doubt regarding the placing of the event listener So, If I have two different panels in my application and each have two buttons. Should I define my my event listeners for the two buttons and their subsequent actions in the controller OR Should I be placing the listeners in the individual view itself?
:god:
2


카일(임광열)  9 days ago
@인치 아티클 고마워요! 찬찬히 읽어볼게요 :slightly_smiling_face:
:+1:
1


파노(전환오)  9 days ago
재사용성을 놓고 봤을때 다른 컨트롤러가 붙어도 동작이 가능하려면 뷰는 렌더링만 담당하는게 좋을것같네요
:pray:
2
:god:
2


파노(전환오)  9 days ago
동작에 변화를 주려면 컨트롤러단만 보면 되니까 유지보수도 쉬워질것같아요. (edited) 
:king:
2


파노(전환오)  9 days ago
https://medium.com/@jang.wangsu/%EC%84%A4%EA%B3%84-%EC%9A%A9%EC%96%B4-%EC%9D%91%EC[…]7%91%EB%8F%84%EC%99%80-%EA%B2%B0%ED%95%A9%EB%8F%84-b5e2b7b210ff
MediumMedium
[설계 용어] 응집도와 결합도
High Cohesion, Low Coupling, 응집도와 결합도 라는 설계관련 용어는 프로그래밍에 익숙하지 않은 사람들에게는 쉽게 익숙해지기가 처음에는 어려울 것 같아요.
Reading time
7 min read
Oct 7th, 2020 (169 kB)
https://miro.medium.com/max/1200/1*0GRGRKqopkdt6anDGwESWQ.png

서니(박선희)  9 days ago
@티케(조은현) 저희는 View 부분에 이벤트 리스너를 넣었습니다. 사용자에게 보여지는 부분과 관련되는 로직이라고 생각해서 View 에서 사용자의 입력을 받는 것이 맞다고 생각했고, View 에서는 click 과 같은 이벤트를 받아서 컨트롤러에 전달하고, 그 이벤트에 대한 핸들링은 Controller 에서 처리하는 식으로 했어요.

파노(전환오)  9 days ago
이거 보고있는데 좋은거같아여

카일(임광열)  9 days ago
다들 감사합니다 ! 데일리 미팅 후에 차근차근 읽어보고 또 얘기해 봐야겠네요 ㅎㅎ

티케(조은현)  9 days ago
@서니(박선희) 추가로 덧붙이자면 저희는 컨트롤러의 부분은 정말로 뷰와 모델을 연결해주는 역할이라고만 생각해서 이벤트를 걸어주는 것은 View에서, 처리하는 것은 Controller에서 했습니다.
